// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN7ZJGWgdtrwYT78YFU8f_ldILsLgqNGA',
    appId: '1:60784874372:android:f64305be85ca9941f303d1',
    messagingSenderId: '60784874372',
    projectId: 'mymess-7b167',
    databaseURL: 'https://mymess-7b167-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mymess-7b167.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC09XgwRPuwl8Fs6w1C7zE0qDg5n8_lNk',
    appId: '1:60784874372:ios:8f014d697c36b3d8f303d1',
    messagingSenderId: '60784874372',
    projectId: 'mymess-7b167',
    databaseURL: 'https://mymess-7b167-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mymess-7b167.firebasestorage.app',
    androidClientId: '60784874372-pnl9khs0btm4b3915u8dgjemh6da1tqe.apps.googleusercontent.com',
    iosClientId: '60784874372-o58l0dr4qd8qhd5891acl7ji1lavsd62.apps.googleusercontent.com',
    iosBundleId: 'com.metaop.mymessflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC09XgwRPuwl8Fs6w1C7zE0qDg5n8_lNk',
    appId: '1:60784874372:ios:8f014d697c36b3d8f303d1',
    messagingSenderId: '60784874372',
    projectId: 'mymess-7b167',
    databaseURL: 'https://mymess-7b167-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mymess-7b167.firebasestorage.app',
    androidClientId: '60784874372-pnl9khs0btm4b3915u8dgjemh6da1tqe.apps.googleusercontent.com',
    iosClientId: '60784874372-o58l0dr4qd8qhd5891acl7ji1lavsd62.apps.googleusercontent.com',
    iosBundleId: 'com.metaop.mymessflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUAPDMjpZBdVg-omujqQKvaeX3vznbeFI',
    appId: '1:60784874372:web:56bed9eef503aabaf303d1',
    messagingSenderId: '60784874372',
    projectId: 'mymess-7b167',
    authDomain: 'mymess-7b167.firebaseapp.com',
    databaseURL: 'https://mymess-7b167-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mymess-7b167.firebasestorage.app',
    measurementId: 'G-M3V6HFLF1T',
  );
}
